# Executar o playbook: ansible-playbook -i production.yaml ping.yaml
---
all:
  hosts:
    #localhost:
    172.17.0.2:
      ansible_user: root
      ansible_ssh_private_key_file: /home/paulo/.ssh/id_rsa
#    172.17.0.3:
#  vars:
#    ansible_user: your_username
#    ansible_ssh_private_key_file: /path/to/your/private/key

#webservers:

#dbservers:
